name: 'meu_projeto_dbt'
version: '1.0.0'
config-version: 2

profile: 'meu_projeto_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  meu_projeto_dbt:
    raw:
      enabled: true
      materialized: view
      +docs:
        node_color: "#cd7f32"

    staging:
      enabled: true
      materialized: view
      +docs:
        node_color: "#c0c0c0"

    intermediate:
      enabled: true
      materialized: view
      +docs:
        node_color: "#f5e6a8"

    marts:
      enabled: true
      schema:  gold
      materialized: table
      +docs:
        node_color: "#e6b530"

